stages:
  - test
.job:
  image: node:14
  stage: test
  before_script:
    - cd $DIR
    - npm install
  script:
    - npm run lint
    - npm run test:ci
  cache:
    key: $DIR
    paths:
      - $DIR/node_modules/

include:
  - local: '/client/.gitlab-ci.yml'
  - local: '/server/.gitlab-ci.yml'